### ISSUE TITLE
difference between Dynamic-AutoDeepLab and original AutoDeepLab

### ISSUE THREAD

**Issue by pawopawo** [HankKung/Auto-Dynamic-DeepLab#1]
Thanks for your excellent work!

What is the difference between `Dynamic-AutoDeepLab` and the [original auto deeplab](https://github.com/NoamRosenberg/AutoML)

**Comment by HankKung** [comment]
Hi, thanks for your attention! It's an ongoing development of a variant of NAS, which is based on Auto-DeepLab. We'll show more details when it is published ASAP.
